apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
  labels:
    app: admiteed
  name: admiteed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admiteed
subjects:
- kind: ServiceAccount
  name: admiteed
  namespace: default