apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: admiteed
  name: admiteed
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - daemonsets
  - replicasets
  - deployments
  verbs:
  - get
  - list
- apiGroups:
  - validating.example.com
  resources:
  - smooths
  verbs:
  - get
  - list