apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app: admiteed
  name: admiteed-smooth
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: "ca"
    service:
      name: admiteed
      namespace: default
      path: /admission/smooth
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: admiteed.example.com
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
