apiVersion: validating.example.com/v1alpha1
kind: Smooth
metadata:
  name: test
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test
  interval: 10
  rules:
    - address: "manage.example.com"
      path: "/UpdateIsLock"
      method: "post"
      body: "deploymentName"
      expect: "false"
    - port: "8080"
      path: "/isolation"
      method: "post"
      body: "true"
      expect: "success"
    - port: "8080"
      path: "/empty"
      method: "get"
      expect: "success"